services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ptTenpo
      POSTGRES_USER: tenpo
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "9090:8080"

  app:
    build: .
    container_name: tenpo-app
    depends_on:
      - postgres_db
      - redis_cache
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/ptTenpo
      SPRING_DATASOURCE_USERNAME: tenpo
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_REDIS_HOST: redis_cache
      SPRING_REDIS_PORT: 6379
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
    ports:
      - "8080:8080"

volumes:
  postgres_data:
